server:
  port: 8084
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: 78xhdtls!
    key-store-type: PKCS12
    key-alias: mini-finance-key

spring:
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://postgres:5432/fintech_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: 5000
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 5